# Generated by Django 4.0.6 on 2022-08-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_devices', '0002_rename_author_device_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='device_pic'),
        ),
    ]
