# Generated by Django 4.1 on 2022-08-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_devices', '0005_remove_device_image_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='device'),
        ),
    ]
