# Generated by Django 4.1 on 2022-08-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_devices', '0006_alter_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
