# Generated by Django 4.1 on 2022-08-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_devices', '0007_alter_device_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='Image',
            new_name='image',
        ),
    ]
