# Generated by Django 4.0.6 on 2022-08-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_devices', '0008_rename_image_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
